### ISSUE TITLE
Does this Utility work with the current firmware?

### ISSUE THREAD

**Issue by m-r-m-s** [dcower/mf-utils#3]
Hi @dcower I wanted to confirm the mf-utils work on the most current firmware 2.0.3? Looking forward to checking this project out.

**Comment by RickTaylor79** [comment]
I just tried it out on 2.1.4 and it worked for me. The un-smoothed wavetables are really unpleasant (in a good way!)

**Comment by gminorcoles** [comment]
how about the 3.0 firmware?

**Comment by dcower** [comment]
Thanks for testing, @modularsamples!

@gminorcoles: I just tested with `MicroFreak_Firmware_Update_3_0_6_1069.mff`, and it works for me now after applying a small fix (one of the files in the firmware had bytes the code didn't expect). If you re-download, it should work for v3.0 now.

**Comment by dcower** [comment]
I'll close this for now, but if there's a new firmware version feel free to reopen and I'll test again. Thanks!
